package sample;

import javassist.offload.Intrinsic;
import javassist.offload.javatoc.CCode;
import javassist.offload.Code;
import javassist.offload.javatoc.StdDriver;
import javassist.offload.lib.Util;

public class AnnotationIntrinsic {
        
	@Intrinsic
	public static void repeat(Object niter, Object exp) {
		if (CCode.inTranslation()) {
			CCode cc = CCode.make("// code generated by @Intrinsic").newLine();
			for (int i = 0; i < 5; i++) {
				cc.add("// #" + i + "\n");
				cc.add((Code)exp).add(";\n");
			}
			cc.emit();
		}
	}
		
    public static void main(String[] args) throws Exception {
    	new StdDriver().invoke(() -> {
    		Util.printer.p("Hello, Annotation Intrinsic").ln();
    		repeat(5, Util.printer.p("kick!").ln());
    	});
    }
	
}
